# sudo cp /usr/share/X11/xorg.conf.d/70-synaptics.conf /etc/X11/xorg.conf.d/70-synaptics.conf
Section "InputClass"
    Identifier "touchpad"
    Driver "synaptics"
    MatchIsTouchpad "on"
    Option "MinSpeed" "0.7"
    Option "MaxSpeed" "0.7"
    Option "AccelFactor" "1"
    Option "TouchpadEmulation" "1"
    Option "FingerHigh" "5"
    Option "FingerLow" "5"
    Option "TapButton1" "1"
    Option "TapButton2" "2"
    Option "TapButton3" "3"
EndSection
